### ISSUE TITLE
Delete resellers

### ISSUE THREAD

**Issue by PeterDepreitere** [Artilium/GiG-ePortal#21]

**Comment by yveskerwyn** [comment]
When deleting a reseller also delete the account used for that reseller using following blueprint:

```
actions:
  - action uninstall
    actor: account
    service: {account-name}
```

Note: currently the e-portal uses the same account for all resellers.
