### ISSUE TITLE
Delete VDCs

### ISSUE THREAD

**Issue by PeterDepreitere** [Artilium/GiG-ePortal#22]

**Comment by yveskerwyn** [comment]
Following blueprint will delete the VDC with name `{vdc-name}`:

```
actions:
  - action uninstall
    actor: vdc
    service: {vdc-name}
```
