### ISSUE TITLE
Stop Services - Reseller

### ISSUE THREAD

**Issue by PeterDepreitere** [Artilium/GiG-ePortal#30]
Mogelijkheid om op alle niveaus alles te kuisen, met de goede disclaimers dat er geen weg terug meer is:

* Stop Reseller
* Stop Customer en al zijn Products / Services
* Stop Product

En telkens moet alles gewist worden op de G8, maar in ePortal moet het wel blijven bestaan.

**Comment by PeterDepreitere** [comment]
Following blueprint will delete the VDC with name {vdc-name} (dixit @yveskerwyn) :

```
actions:
  - action uninstall
    actor: vdc
    service: {vdc-name}
```

**Comment by PeterDepreitere** [comment]
When deleting a reseller also delete the account used for that reseller using following blueprint:

```
actions:
  - action uninstall
    actor: account
    service: {account-name}
```

Note: currently the e-portal uses the same account for all resellers.
