### ISSUE TITLE
Stop Services - Customer

### ISSUE THREAD

**Issue by PeterDepreitere** [Artilium/GiG-ePortal#31]
Mogelijkheid om op alle niveaus alles te kuisen, met de goede disclaimers dat er geen weg terug meer is:

* Stop Reseller
* Stop Customer en al zijn Products / Services
* Stop Product

En telkens moet alles gewist worden op de G8, maar in ePortal moet het wel blijven bestaan.

**Comment by PeterDepreitere** [comment]
Following blueprint will delete the VDC with name {vdc-name} (dixit @yveskerwyn) :

```
actions:
  - action uninstall
    actor: vdc
    service: {vdc-name}
```
